[[redirects]]
  from = "/ape/*"
  to = "https://white3zz.m3zz.com/:splat"
  status = 200

[[redirects]]
  from = "/bspapp/*"
  to = "https://fund-api-url.rabt.top/http/user-center/:splat"
  status = 200
