/**
 * 游戏大区的配置文件
 */
export const levelConfig = {
  tier: [
    "最强王者",
    "钻石",
    "铂金",
    "黄金",
    "白银",
    "青铜",
    "超凡大师",
    "傲世宗师",
    "黑铁",
  ],
  level: ["Ⅰ", "Ⅱ", "Ⅲ", "Ⅳ", "Ⅴ"],
  game_mod: {
    0: "自定义",
    1: "匹配赛",
    2: "匹配赛",
    8: "匹配赛",
    9: "灵活排位",
    14: "匹配赛",
    31: "人机赛",
    32: "人机赛",
    33: "人机赛",
    34: "人机赛",
    35: "人机赛",
    36: "人机赛",
    52: "人机赛",
    62: "大乱斗",
    63: "大乱斗",
    64: "大乱斗",
    65: "大乱斗",
    100: "匹配赛",
    300: "魄罗大乱斗",
    301: "魄罗大乱斗",
    320: "红月决",
    321: "红月决",
    400: "匹配赛",
    401: "匹配赛",
    402: "匹配赛",
    403: "匹配赛",
    420: "单双排",
    421: "单双排",
    422: "单双排",
    430: "匹配赛",
    431: "匹配赛",
    432: "匹配赛",
    433: "匹配赛",
    440: "灵活排位",
    441: "灵活排位",
    442: "灵活排位",
    450: "大乱斗",
    451: "大乱斗",
    452: "大乱斗",
    460: "匹配赛",
    470: "灵活排位",
    480: "匹配赛",
    600: "红月决",
    601: "红月决",
    610: "暗星:奇点",
    611: "暗星:奇点",
    700: "冠军杯赛",
    701: "冠军杯赛",
    800: "人机赛",
    801: "人机赛",
    810: "人机赛",
    820: "人机赛",
    830: "人机赛",
    840: "人机赛",
    850: "人机赛",
    870: "人机赛",
    880: "人机赛",
    890: "人机赛",
    900: "无限火力",
    901: "无限火力",
    920: "魄罗大乱斗",
    921: "魄罗大乱斗",
    930: "大乱斗",
    931: "大乱斗",
    970: "六杀争夺战",
    1010: "冰雪无限火力",
    1011: "冰雪无限火力",
    1020: "克隆赛",
    1021: "克隆赛",
    1022: "克隆赛",
    1030: "奥德赛",
    1040: "奥德赛",
    1050: "奥德赛",
    1060: "奥德赛",
    1070: "奥德赛",
    1090: "云顶匹配赛",
    1100: "云顶排位赛",
    1130: "云顶狂暴模式",
    1200: "极限闪击",
    1400: "终极魔典",
    1700: "斗魂竞技场",
    1810: "无尽狂潮",
    1900: "无限火力",
    2e3: "新手教程",
    2010: "新手教程",
    2020: "新手教程",
    65535: "未知",
  },
  yunding_mod: {
    1: "匹配赛",
    2: "排位赛",
    3: "狂暴赛",
    4: "双人模式",
    5: "双人排位",
    6: "恭喜发财",
    7: "斗魂锦标赛",
    8: "恭喜发财",
    9: "再战星海",
    10: "云顶5周年时光机",
    11: "发条鸟的试炼",
    12: "英雄之黎明",
  },
};
export const areaMap = {
  1: {
    id: "1",
    strid: "HN1",
    isp: "电信一",
    name: "艾欧尼亚",
    idc: "东莞东城",
    tcls: "257",
    ob: "1",
  },
  3: {
    id: "3",
    strid: "HN2",
    isp: "电信二",
    name: "祖安",
    idc: "杭州东冠",
    tcls: "513",
    ob: "1",
  },
  4: {
    id: "4",
    strid: "HN3",
    isp: "电信三",
    name: "诺克萨斯",
    idc: "东莞大朗",
    tcls: "769",
    ob: "1",
  },
  2: {
    id: "2",
    strid: "WT1",
    isp: "网通一",
    name: "比尔吉沃特",
    idc: "济南担山屯",
    tcls: "258",
    ob: "1",
  },
  6: {
    id: "6",
    strid: "WT2",
    isp: "网通二",
    name: "德玛西亚",
    idc: "济南担山屯",
    tcls: "514",
    ob: "1",
  },
  9: {
    id: "9",
    strid: "WT3",
    isp: "网通三",
    name: "弗雷尔卓德",
    idc: "天津数据中心",
    tcls: "770",
    ob: "1",
  },
  5: {
    id: "5",
    strid: "HN4",
    isp: "电信四",
    name: "班德尔城",
    idc: "成都光华",
    tcls: "1025",
    ob: "0",
  },
  7: {
    id: "7",
    strid: "HN5",
    isp: "电信五",
    name: "皮尔特沃夫",
    idc: "杭州东冠",
    tcls: "1281",
    ob: "0",
  },
  8: {
    id: "8",
    strid: "HN6",
    isp: "电信六",
    name: "战争学院",
    idc: "东莞大朗",
    tcls: "1537",
    ob: "0",
  },
  10: {
    id: "10",
    strid: "HN7",
    isp: "电信七",
    name: "巨神峰",
    idc: "杭州东冠",
    tcls: "1793",
    ob: "0",
  },
  11: {
    id: "11",
    strid: "HN8",
    isp: "电信八",
    name: "雷瑟守备",
    idc: "东莞大朗",
    tcls: "2049",
    ob: "0",
  },
  12: {
    id: "12",
    strid: "WT4",
    isp: "网通四",
    name: "无畏先锋",
    idc: "济南担山屯",
    tcls: "1026",
    ob: "0",
  },
  17: {
    id: "17",
    strid: "HN12",
    isp: "电信十二",
    name: "钢铁烈阳",
    idc: "成都高新",
    tcls: "3073",
    ob: "0",
  },
  13: {
    id: "13",
    strid: "HN9",
    isp: "电信九",
    name: "裁决之地",
    idc: "成都高新",
    tcls: "2305",
    ob: "0",
  },
  14: {
    id: "14",
    strid: "HN10",
    isp: "电信十",
    name: "黑色玫瑰",
    idc: "东莞大朗",
    tcls: "2561",
    ob: "0",
  },
  15: {
    id: "15",
    strid: "HN11",
    isp: "电信十一",
    name: "暗影岛",
    idc: "东莞大朗",
    tcls: "2817",
    ob: "0",
  },
  16: {
    id: "16",
    strid: "WT5",
    isp: "网通五",
    name: "恕瑞玛",
    idc: "天津数据中心",
    tcls: "1282",
    ob: "0",
  },
  19: {
    id: "19",
    strid: "HN14",
    isp: "电信十四",
    name: "均衡教派",
    idc: "南京二长",
    tcls: "3585",
    ob: "0",
  },
  18: {
    id: "18",
    strid: "HN13",
    isp: "电信十三",
    name: "水晶之痕",
    idc: "杭州东冠",
    tcls: "3329",
    ob: "0",
  },
  20: {
    id: "20",
    strid: "WT6",
    isp: "网通六",
    name: "扭曲丛林",
    idc: "天津数据中心",
    tcls: "1538",
    ob: "0",
  },
  21: {
    id: "21",
    strid: "EDU1",
    isp: "教育网",
    name: "教育网专区",
    idc: "上海南汇",
    tcls: "65539",
    ob: "0",
  },
  22: {
    id: "22",
    strid: "HN15",
    isp: "电信十五",
    name: "影流",
    idc: "南京二长",
    tcls: "3841",
    ob: "0",
  },
  23: {
    id: "23",
    strid: "HN16",
    isp: "电信十六",
    name: "守望之海",
    idc: "南京二长",
    tcls: "4097",
    ob: "0",
  },
  24: {
    id: "24",
    strid: "HN17",
    isp: "电信十七",
    name: "征服之海",
    idc: "东莞大朗",
    tcls: "4353",
    ob: "0",
  },
  25: {
    id: "25",
    strid: "HN18",
    isp: "电信十八",
    name: "卡拉曼达",
    idc: "深圳蛇口",
    tcls: "4609",
    ob: "0",
  },
  26: {
    id: "26",
    strid: "WT7",
    isp: "网通七",
    name: "巨龙之巢",
    idc: "天津数据中心",
    tcls: "1794",
    ob: "0",
  },
  27: {
    id: "27",
    strid: "HN19",
    isp: "电信十九",
    name: "皮城警备",
    idc: "成都高新",
    tcls: "4865",
    ob: "0",
  },
  30: {
    id: "30",
    strid: "BGP1",
    isp: "全网络大区一",
    name: "男爵领域",
    idc: "上海腾讯宝信DC",
    // "tcls": "773",
    tcls: "261",
    ob: "0",
  },
  31: {
    id: "31",
    strid: "BGP2",
    isp: "全网络大区二",
    name: "峡谷之巅",
    idc: "上海腾讯宝信DC",
    tcls: "517",
    ob: "0",
  },
};

export const platformMap = {
  HN1: "艾欧尼亚",
  HN10: "黑色玫瑰",
  NJ100: "联盟一区",
  GZ100: "联盟二区",
  CQ100: "联盟三区",
  TJ100: "联盟四区",
  TJ101: "联盟五区",
};
export const platform2areaId = {
  HN1: "1",
  HN10: "14",
  NJ100: "3",
  GZ100: "4",
  CQ100: "5",
  TJ100: "2",
  TJ101: "6",
};

export const defaultUser = [];

export const tabList = [
  {
    name: "峡谷",
    value: "user",
  },
  {
    name: "云顶",
    value: "batch",
  },
  {
    name: "批量查询",
    value: "batch",
  },
];

export const DisplayMode = [
  { label: "极简", value: "mini" },
  { label: "普通", value: "normal" },
  { label: "详细", value: "detailed" },
];

export const lzyumiA = `https://a.lzyumi.top`;

export const baseUrlList = [
  {
    name: "地址1",
    value: lzyumiA,
  },
  {
    name: "地址2",
    value: "https://6.lzelo.top",
  },
  {
    name: "地址3",
    value: lzyumiA,
  },
];

export const S5ChessList = [{"TFTID":"330","chessId":"2","displayName":"奥拉夫","hero_EN_name":"TFT5_Olaf","title":"狂战士","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/330.png","jobIds":"5009","raceIds":"5114","skillIntroduce":"奥拉夫的每1%已损失生命值会为他提供额外2%/3%/4%攻击速度，并且他的每次攻击会为他治疗20/30/70生命值。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/olaf-berserker-rage.png","skillName":"狂战之怒","skillType":"被动","price":"1","recEquip":""},{"TFTID":"352","chessId":"3","displayName":"加里奥","hero_EN_name":"TFT5_Galio","title":"正义巨像","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/352.png","jobIds":"5007","raceIds":"5110,5114","skillIntroduce":"充能周围的区域2.5秒，嘲讽其中的敌人们并获得55%/60%/95%伤害减免。在释放这次充能时，对3格内的所有敌人们造成200/300/1500魔法伤害并治疗自身60%的已格挡伤害。\r\n嘲讽：如果敌人能够攻击且已将嘲讽者纳入攻击距离内，则必须攻击嘲讽者。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/galio_w.png","skillName":"杜朗护盾","skillType":"主动","price":"4","recEquip":""},{"TFTID":"323","chessId":"8","displayName":"弗拉基米尔","hero_EN_name":"TFT5_Vladimir","title":"猩红收割者","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/323.png","jobIds":"5005","raceIds":"5102","skillIntroduce":"【弗拉基米尔】对目标造成300/420/540魔法伤害，并且治疗自身200/250/350的生命值。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/vladimir-transfusion.png","skillName":"鲜血转换","skillType":"主动","price":"1","recEquip":""},{"TFTID":"332","chessId":"9","displayName":"费德提克","hero_EN_name":"TFT5_Fiddlesticks","title":"末日使者","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/332.png","jobIds":"5010","raceIds":"5106,5113","skillIntroduce":"在短暂的引导后，费德提克传送到他的目标身后并召唤持续4秒的杀人鸦群，每秒对其中的所有敌人造成150/200/750魔法伤害。死于鸦群的每个敌人都会使其持续时间延长1秒并治疗费德提克，数额相当于该敌人20% / 25% / 50%的最大生命值。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/fiddlesticks-crowstorm.png","skillName":"群鸦风暴","skillType":"主动","price":"4","recEquip":""},{"TFTID":"287","chessId":"10","displayName":"凯尔","hero_EN_name":"TFT5_Kayle","title":"正义天使","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/287.png","jobIds":"5004","raceIds":"5107","skillIntroduce":"【凯尔】每经过5/5/1秒，就会进行一次飞升，以获得额外加成，直到她完全登神。\r\n第1次施放：攻击造成凯尔50/60/1000%攻击力的额外真实伤害。\r\n第2次施放：攻击会引爆目标周围，对邻格的敌人造成她攻击力的伤害和额外真实伤害。\r\n第3次施放：每第12次攻击会为凯尔提供持续1秒的伤害免疫效果。\r\n第4次施放：命中时会在目标附近引发剑雨，造成90/150/4000魔法伤害。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/kayle-divine-ascent.png","skillName":"登神长阶","skillType":"被动","price":"5","recEquip":""},{"TFTID":"311","chessId":"16","displayName":"索拉卡","hero_EN_name":"TFT5_Soraka","title":"众星之子","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/311.png","jobIds":"5005","raceIds":"5108","skillIntroduce":"【索拉卡】使具有最高当前法力值的英雄周围平静下来，对命中的所有敌人造成200/275/400魔法伤害并使他们下一个技能的法力消耗提升33/35/50%。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/soraka-equinox.png","skillName":"星体结界","skillType":"主动","price":"2","recEquip":""},{"TFTID":"314","chessId":"17","displayName":"提莫","hero_EN_name":"TFT5_Teemo","title":"迅捷斥候","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/314.png","jobIds":"5012,5006","raceIds":"5104","skillIntroduce":"提莫在一名随机敌人周围布下5/6/42炼狱烈魂。当一名敌人接近炼狱烈魂时（或在3秒之后），它会爆炸，对附近的敌人们造成120/160/666魔法伤害并降低他们50%攻击速度。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/teemo-teemos-cruelty.png","skillName":"提莫的交易","skillType":"主动","price":"6","recEquip":""},{"TFTID":"333","chessId":"18","displayName":"崔丝塔娜","hero_EN_name":"TFT5_Tristana","title":"麦林炮手","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/333.png","jobIds":"5015","raceIds":"5104","skillIntroduce":"崔丝塔娜跳到相距最远的敌人身后，将其选为目标并为她自己提供120/130/140%攻击速度，持续4秒。如果她的邻格有一名敌人，她会转而跳到尽可能远离所有敌人的位置。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/tristana-rocket-jump.png","skillName":"火箭跳跃","skillType":"主动","price":"2","recEquip":""},{"TFTID":"303","chessId":"20","displayName":"努努和威朗普","hero_EN_name":"TFT5_Nunu","title":"雪原双子","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/303.png","jobIds":"5003","raceIds":"5106","skillIntroduce":"【威朗普】撕咬他的目标，造成450/700/1600魔法伤害。如果【威朗普】的目标的生命值低于【威朗普】在撕咬前的生命值，那么这个技能会造成额外的50%魔法伤害并变为真实伤害。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/nunu-consume.jpg","skillName":"吞噬","skillType":"主动","price":"3","recEquip":""},{"TFTID":"339","chessId":"21","displayName":"厄运小姐","hero_EN_name":"TFT5_MissFortune","title":"赏金猎人","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/339.png","jobIds":"5015","raceIds":"5101","skillIntroduce":"厄运小姐在她目标周围降下4波弹雨，对区域内的所有敌人共造成250/375/550魔法伤害，并使其将要受到的治疗效果降低50%，持续6秒。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/miss-fortune-make-it-rain.png","skillName":"枪林弹雨","skillType":"主动","price":"3","recEquip":""},{"TFTID":"273","chessId":"22","displayName":"艾希","hero_EN_name":"TFT5_Ashe","title":"寒冰射手","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/273.png","jobIds":"5002","raceIds":"5110","skillIntroduce":"【艾希】朝相距最远的一名敌人发射一支箭矢，箭矢会在首次命中敌人时爆炸，造成300/450/750魔法伤害和1/2/2.5秒晕眩效果，如果箭矢飞行超过了5个，则眩晕时间将延长一倍，1格以内的敌人会受到50%的效果。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/ashe-enchanted-arrow.png","skillName":"魔法水晶箭","skillType":"主动","price":"3","recEquip":""},{"TFTID":"283","chessId":"24","displayName":"贾克斯","hero_EN_name":"TFT5_Jax","title":"武器大师","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/283.png","jobIds":"5009","raceIds":"5111","skillIntroduce":"【贾克斯】猛击他的目标，造成他220/240/500%攻击力的伤害并获得可叠加的20/30/100%攻击速度，持续到战斗环节结束为止。如果【贾克斯】的攻击距离内没有目标，那么他会跃向相距最近的敌人。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/jax-empowered-strike.png","skillName":"强化打击","skillType":"主动","price":"4","recEquip":""},{"TFTID":"334","chessId":"39","displayName":"艾瑞莉娅","hero_EN_name":"TFT5_Irelia","title":"刀锋舞者","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/334.png","jobIds":"5004","raceIds":"5114","skillIntroduce":"艾瑞莉娅将自身笼罩在剑刃中，持续4秒，并获得30%/40%/50%伤害减免，在她每次攻击时提升10%，至多获得80%伤害减免。当这个效果结束时，她会打击目标以造成250/400/650魔法伤害。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/irelia-defiant-dance.png","skillName":"距破之舞","skillType":"主动","price":"2","recEquip":""},{"TFTID":"285","chessId":"43","displayName":"卡尔玛","hero_EN_name":"TFT5_Karma","title":"天启者","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/285.png","jobIds":"5006","raceIds":"5108","skillIntroduce":"【卡尔玛】朝随机一位敌人发射一团能量爆裂，在首次命中敌人时爆炸，对相邻敌人造成230/300/850魔法伤害，并使卡尔玛的最大法力值降低15/15/40（最低降低至10点）。卡尔玛会对每第三次施放进行强化，使其转而发射3团而非1团能量爆裂至不同的目标。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/karma-soulflare.png","skillName":"灵光闪耀","skillType":"主动","price":"4","recEquip":""},{"TFTID":"302","chessId":"56","displayName":"魔腾","hero_EN_name":"TFT5_Nocturne","title":"永恒梦魇","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/302.png","jobIds":"5001","raceIds":"5113","skillIntroduce":"被动：【魔腾】的每第三次攻击会斩击邻格的所有敌人，造成他70%攻击力及额外100/100/100的伤害，并为自身提供相当于此次攻击100%/100%/100%实际伤害值的治疗效果。如果只面对一个目标，魔腾将会提升他35%/35%/35%的攻击速度。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/nocturne-umbra-blades.png","skillName":"暗影之刃","skillType":"被动","price":"3","recEquip":""},{"TFTID":"274","chessId":"63","displayName":"布兰德","hero_EN_name":"TFT5_Brand","title":"复仇焰魂","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/274.png","jobIds":"5008","raceIds":"5106","skillIntroduce":"布兰德朝相距最近且未带有【火焰烙印】的敌人放出一颗火球，给其施加烙印，以在12秒里持续造成共650/950/1750的魔法伤害。带有【火焰烙印】的敌人们会被降低40/50/70%的魔法抗性。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/brand-sear.png","skillName":"火焰烙印","skillType":"主动","price":"2","recEquip":""},{"TFTID":"293","chessId":"64","displayName":"李青","hero_EN_name":"TFT5_LeeSin","title":"盲僧","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/293.png","jobIds":"5009","raceIds":"5102","skillIntroduce":"【李青】猛击地面，对附近的敌人们造成200/350/600魔法伤害并使其攻击速度减缓50%，持续4秒。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/lee-sin-cripple.png","skillName":"天雷破","skillType":"主动","price":"3","recEquip":""},{"TFTID":"319","chessId":"67","displayName":"薇恩","hero_EN_name":"TFT5_Vayne","title":"暗夜猎手","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/319.png","jobIds":"5002","raceIds":"5101","skillIntroduce":"【薇恩】的攻击会施加可叠加的圣银弩箭效果。在达到第三层时，会消耗目标的所有层数并造成70/85/100额外真实伤害。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/vayne-silver-bolts.png","skillName":"终极时刻","skillType":"主动","price":"1","recEquip":""},{"TFTID":"281","chessId":"74","displayName":"黑默丁格","hero_EN_name":"TFT5_Heimerdinger","title":"大发明家","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/281.png","jobIds":"5014,5005","raceIds":"5110","skillIntroduce":"【黑默丁格】强化他的龙龙宝贝的下一次攻击。龙龙宝贝的充能攻击会喷出3颗火球横穿战场，造成425/600/3333魔法伤害并灼烧敌人们，在6秒内造成其18%最大生命值的真实伤害，在此期间降低50%治疗效果。\r\n如果黑默丁格连一个龙龙宝贝都没有，那么这个技能将生成一个作为替代。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/heimerdinger-upgrade.png","skillName":"升级！！！","skillType":"主动","price":"5","recEquip":""},{"TFTID":"301","chessId":"76","displayName":"奈德丽","hero_EN_name":"TFT5_Nidalee","title":"狂野女猎手","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/301.png","jobIds":"5009","raceIds":"5108","skillIntroduce":"【奈德丽】变形为一只美洲狮并跳到最低生命值的敌人身后。在美洲狮形态下，【奈德丽】获得40%闪避几率，30/50/75%攻击速度，并且她的攻击变为近战，每第4次攻击造成200/300/600额外魔法伤害。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/nidalee-aspect-of-the-cougar.png","skillName":"美洲狮形态","skillType":"主动","price":"3","recEquip":""},{"TFTID":"317","chessId":"77","displayName":"乌迪尔","hero_EN_name":"TFT5_Udyr","title":"兽灵行者","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/317.png","jobIds":"5009","raceIds":"5110","skillIntroduce":"【乌迪尔】在每次施放技能时，都会在灵龟姿态和猛虎姿态之间切换，获得以下收益：\r\n灵龟姿态：获得250/350/600护盾值，持续4秒。\r\n猛虎姿态：他的下次普攻进行3次快速打击，造成他120/130/180%攻击力的伤害。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/udyr-feral-instinct.png","skillName":"蛮野本能","skillType":"主动","price":"1","recEquip":""},{"TFTID":"305","chessId":"78","displayName":"波比","hero_EN_name":"TFT5_Poppy","title":"圣锤之毅","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/305.png","jobIds":"5007","raceIds":"5104","skillIntroduce":"【波比】对相距最远的敌人扔出她的小圆盾，造成150/250/450魔法伤害。随后小圆盾会弹回，为【波比】提供250/375/525护盾值。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/poppy-buckler-toss.png","skillName":"圆盾投掷","skillType":"主动","price":"1","recEquip":""},{"TFTID":"279","chessId":"79","displayName":"古拉加斯","hero_EN_name":"TFT5_Gragas","title":"酒桶","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/279.png","jobIds":"5003","raceIds":"5108","skillIntroduce":"【古拉加斯】畅饮他的佳酿，为他提供35/45/60%伤害减免，持续4秒，并使他的下次普攻造成175/250/475额外魔法伤害。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/gragas-drunken-rage.png","skillName":"醉酒狂暴","skillType":"主动","price":"1","recEquip":""},{"TFTID":"288","chessId":"85","displayName":"凯南","hero_EN_name":"TFT5_Kennen","title":"狂暴之心","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/288.png","jobIds":"5009","raceIds":"5104","skillIntroduce":"【凯南】将自身包裹在烈焰中，冲向相距最远的敌人。他会对途经的敌人们施加1.5/2/2.5秒的晕眩效果，造成150/225/350的魔法伤害。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/kennen-flame-rush.png","skillName":"烈焰猛冲","skillType":"主动","price":"2","recEquip":""},{"TFTID":"278","chessId":"86","displayName":"盖伦","hero_EN_name":"TFT5_Garen","title":"德玛西亚之力","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/278.png","jobIds":"5007","raceIds":"5108,5116","skillIntroduce":"【盖伦】召唤一把巨剑降临，来对他目标周围的一个大型区域进行打击，对区域内的所有敌人造成各目标25/35/200%最大生命值的魔法伤害，并使其魔法抗性降低60%，持续8秒。【盖伦】随后会获得持续4秒的护盾，护盾值相当于其35/45/200%的最大生命值。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/garen-god-lions-justice.png","skillName":"神狮裁决","skillType":"主动","price":"5","recEquip":""},{"TFTID":"294","chessId":"89","displayName":"蕾欧娜","hero_EN_name":"TFT5_Leona","title":"曙光女神","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/294.png","jobIds":"5007","raceIds":"5107","skillIntroduce":"【蕾欧娜】举起她的盾牌，使所有即将到来的伤害减少30/40/120，持续4秒。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/leona-solar-barrier.png","skillName":"烈阳屏障","skillType":"主动","price":"1","recEquip":""},{"TFTID":"307","chessId":"92","displayName":"锐雯","hero_EN_name":"TFT5_Riven","title":"放逐之刃","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/307.png","jobIds":"5004","raceIds":"5108","skillIntroduce":"【锐雯】强化她的剑刃，对附近的敌人们造成1.5秒晕眩和100/200/300魔法伤害。在接下来的8秒里，【锐雯】获得90/100/115%攻击力。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/riven-blade-of-the-dawn.png","skillName":"黎明之刃","skillType":"主动","price":"3","recEquip":""},{"TFTID":"297","chessId":"99","displayName":"拉克丝","hero_EN_name":"TFT5_Lux","title":"光辉女郎","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/297.png","jobIds":"5010","raceIds":"5107","skillIntroduce":"【拉克丝】朝相距最远的友军掷出她的魔杖，魔杖会在接触到该友军后折返。【拉克丝】和每位被魔杖触碰过的魔杖都会获得120/180/360护盾值，持续3秒。拉克丝的下一次攻击会造成额外400/600/1000的魔法伤害。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/lux-prismatic-barrier.png","skillName":"曲光屏障","skillType":"主动","price":"3","recEquip":""},{"TFTID":"324","chessId":"106","displayName":"沃利贝尔","hero_EN_name":"TFT5_Volibear","title":"不灭狂雷","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/324.png","jobIds":"5003","raceIds":"5113","skillIntroduce":"【沃利贝尔】跃向他的目标，然后猛击他周围一个大型区域的地面，造成125/250/5000魔法伤害，并击飞和晕眩敌人们2/3.5/10秒。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/volibear-doombringer.png","skillName":"末日使者","skillType":"主动","price":"5","recEquip":""},{"TFTID":"318","chessId":"110","displayName":"韦鲁斯","hero_EN_name":"TFT5_Varus","title":"惩戒之箭","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/318.png","jobIds":"5002","raceIds":"5107","skillIntroduce":"【韦鲁斯】在他的目标四周发射一阵箭雨，造成基于其攻击力150/155/165%的物理伤害，该区域内韦鲁斯和友军会受到祝福，在接下来的6秒内共计会造成40/60/90的额外魔法伤害。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/varus-hail-of-arrows.png","skillName":"圣光箭雨","skillType":"主动","price":"2","recEquip":""},{"TFTID":"300","chessId":"111","displayName":"诺提勒斯","hero_EN_name":"TFT5_Nautilus","title":"深海泰坦","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/300.png","jobIds":"5007","raceIds":"5111","skillIntroduce":"【诺提勒斯】引爆目标脚下的地面，将其击飞并晕眩3/4/6秒，并造成200/300/750魔法伤害。目标邻格的敌人们会受到这个技能的一半效果。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/nautilus-anchor-slam.png","skillName":"巨锚猛击","skillType":"主动","price":"2","recEquip":""},{"TFTID":"309","chessId":"113","displayName":"瑟庄妮","hero_EN_name":"TFT5_Sejuani","title":"北地之怒","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/309.png","jobIds":"5011,5003","raceIds":"5102","skillIntroduce":"【瑟庄妮】为坐骑充能，造成300/450/750的魔法伤害，并晕眩目标2/3/4秒，随后她会获得冰霜护甲，来为她提供60/100/200护甲和魔法抗性，持续4秒。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/sejuani-fury-of-the-north.png","skillName":"北地之怒","skillType":"主动","price":"2","recEquip":""},{"TFTID":"327","chessId":"115","displayName":"吉格斯","hero_EN_name":"TFT5_Ziggs","title":"爆破鬼才","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/327.png","jobIds":"5008","raceIds":"5104","skillIntroduce":"【吉格斯】朝他的目标扔出一颗奥术炸弹，造成250/375/550魔法伤害并将其晕眩0.5秒。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/ziggs-arcane-bomb.png","skillName":"奥术炸弹","skillType":"主动","price":"1","recEquip":""},{"TFTID":"296","chessId":"117","displayName":"璐璐","hero_EN_name":"TFT5_Lulu","title":"仙灵女巫","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/296.png","jobIds":"5010","raceIds":"5104","skillIntroduce":"【璐璐】为相距最近的3/4/6个单位各施放一个附身符咒，如果这个符咒附身在友方单位身上，则会提供持续4秒的70/80/120%的额外攻击速度，持续5秒。如果这个符咒附身在敌方单位身上，则会将该敌人晕眩并变为一直温顺的猫咪，持续1.5/2/2.5秒，并使其受到的伤害提升20%。如果附近的单位少于3个，那么璐璐会给自己释放符咒。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/lulu-whimsy.png","skillName":"萌力护身！","skillType":"主动","price":"3","recEquip":""},{"TFTID":"277","chessId":"119","displayName":"德莱文","hero_EN_name":"TFT5_Draven","title":"荣耀行刑官","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/277.png","jobIds":"5004","raceIds":"5101","skillIntroduce":"【德莱文】开始旋转他的一把飞斧，使他的下次攻击在命中时造成基于攻击力140/150/400%附加125/200/700的额外物理伤害。\r\n飞斧将在命中目标之后折返至他所在的位置，并且如果【德莱文】接住了这把飞斧，那么将刷新这一增益效果。\r\n【德莱文】至多能够同时旋转2把飞斧。\r\n【德莱文】被动：无视目标的50%护甲值。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/draven-spinning-axes.png","skillName":"旋转飞斧","skillType":"主动","price":"4","recEquip":""},{"TFTID":"280","chessId":"120","displayName":"赫卡里姆","hero_EN_name":"TFT5_Hecarim","title":"战争之影","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/280.png","jobIds":"5011","raceIds":"5101","skillIntroduce":"【赫卡里姆】生成一个环绕自身的光环，持续3秒。光环内的每名敌人都会受到200 / 400 / 600魔法伤害，并且赫卡里姆会在此期间持续回复自身共200 / 225 / 250生命值。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/hecarim-spirit-of-dread.png","skillName":"恐惧之灵","skillType":"主动","price":"2","recEquip":""},{"TFTID":"289","chessId":"121","displayName":"卡兹克","hero_EN_name":"TFT5_Khazix","title":"虚空掠夺者","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/289.png","jobIds":"5001","raceIds":"5108","skillIntroduce":"【卡兹克】斩击相距最近的敌人，造成250/350/450魔法伤害。如果在该敌人的邻格内没有其它敌人，那么这个伤害会提升至750/1050/1350。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/khazix-taste-their-fear.png","skillName":"品尝恐惧","skillType":"主动","price":"1","recEquip":""},{"TFTID":"276","chessId":"131","displayName":"黛安娜","hero_EN_name":"TFT5_Diana","title":"皎月女神","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/276.png","jobIds":"5001","raceIds":"5102","skillIntroduce":"【黛安娜】召唤月光降临，拉拽附近的敌人们、使其短暂晕眩2/2.5/4秒，并对其造成300/450/2000魔法伤害。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/diana-moonfall.png","skillName":"月之降临","skillType":"主动","price":"4","recEquip":""},{"TFTID":"312","chessId":"134","displayName":"辛德拉","hero_EN_name":"TFT5_Syndra","title":"黑暗元首","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/312.png","jobIds":"5006","raceIds":"5107","skillIntroduce":"【辛德拉】抓取相距最近的敌人然后将其扔出投向最远的敌人，在碰撞时造成250/350/650魔法伤害和2/2.5/4秒眩晕时间。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/syndra-force-of-will.png","skillName":"驱使念力","skillType":"主动","price":"2","recEquip":""},{"TFTID":"328","chessId":"143","displayName":"婕拉","hero_EN_name":"TFT5_Zyra","title":"荆棘之兴","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/328.png","jobIds":"5008","raceIds":"5110","skillIntroduce":"【婕拉】向最远的敌人发出一串藤蔓，造成200/300/525的魔法伤害，使所有被击中的敌人昏迷2/2.5/3秒。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/zyra-grasping-roots.png","skillName":"致命尖刺","skillType":"主动","price":"3","recEquip":""},{"TFTID":"326","chessId":"157","displayName":"亚索","hero_EN_name":"TFT5_Yasuo","title":"疾风剑豪","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/326.png","jobIds":"5004","raceIds":"5102","skillIntroduce":"【亚索】对目标进行打击，造成250/350/550魔法伤害并强化他的剑刃6秒，使他的普攻在接下来的战斗中造成额外25/35/55真实伤害。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/yasuo-burning-blade.png","skillName":"灼烧之刃","skillType":"主动","price":"3","recEquip":""},{"TFTID":"320","chessId":"161","displayName":"维克兹","hero_EN_name":"TFT5_Velkoz","title":"虚空之眼","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/320.png","jobIds":"5008","raceIds":"5107","skillIntroduce":"【维克兹】发射一道能量射线，在3秒里持续横扫战场，造成共850/1100/4000魔法伤害。射线随着维克兹的星级而扩散，如果附近没有敌人，他将扭转射线的方向。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/velkoz-plasma-fission.png","skillName":"生命形态瓦解射线","skillType":"主动","price":"4","recEquip":""},{"TFTID":"329","chessId":"166","displayName":"阿克尚","hero_EN_name":"TFT5_Akshan","title":"影哨","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/329.png","jobIds":"5002","raceIds":"5114","skillIntroduce":"被动：阿克尚的攻击会使目标的护甲降低50%，持续4秒。\r\n主动：阿克尚发射他的钩爪并朝相距最远的敌人进行无法被选取的摆荡，获得持续4秒的60%/70%/400%攻击速度。在摆荡时，阿克尚将以他的双倍攻速来持续攻击相距最近的敌人。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/akshan-heroic-swing.png","skillName":"骄行荡寇","skillType":"主动","price":"5","recEquip":""},{"TFTID":"321","chessId":"234","displayName":"佛耶戈","hero_EN_name":"TFT5_Viego","title":"破败之王","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/321.png","jobIds":"5001,5009","raceIds":"5101","skillIntroduce":"【佛耶戈】开始污染他目标的灵魂，使其攻击速度降低50%，并且每秒对其造成150/400/2000魔法伤害。【佛耶戈】会不断这么做，直到目标阵亡或他被晕眩为止。当他的猎物阵亡时，会带着满生命值复活并为【佛耶戈】而战，但每秒失去10/5/0%最大生命值。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/viego-sovereigns-domination.png","skillName":"君命已决","skillType":"主动","price":"5","recEquip":""},{"TFTID":"335","chessId":"235","displayName":"赛娜","hero_EN_name":"TFT5_Senna","title":"涤魂圣枪","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/335.png","jobIds":"5015","raceIds":"5114","skillIntroduce":"赛娜朝相距最远的敌人放出黑雾。在途中命中的首个敌人会被晕眩1.5秒，并且所有附近的敌人会受到200 / 300 / 450魔法伤害。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/senna-last-embrace.png","skillName":"无尽厮守","skillType":"主动","price":"1","recEquip":""},{"TFTID":"336","chessId":"236","displayName":"卢锡安","hero_EN_name":"TFT5_Lucian","title":"圣枪游侠","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/336.png","jobIds":"5015","raceIds":"5114","skillIntroduce":"卢锡安面朝相距最远的敌人，然后在4秒里朝这个方向发射16颗子弹，并会进行冲刺以保持命中敌人。每颗子弹在命中时造成他50% / 50% / 50%攻击力的物理伤害和40/70/400魔法伤害。卢锡安还会基于他的攻击速度发射额外的子弹。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/lucian-the-culling.png","skillName":"圣枪洗礼","skillType":"主动","price":"4","recEquip":""},{"TFTID":"291","chessId":"240","displayName":"克烈","hero_EN_name":"TFT5_Kled","title":"暴怒骑士","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/291.png","jobIds":"5011","raceIds":"5104","skillIntroduce":"【克烈】骑着斯嘎尔进入战斗，为他提供一层80%最大生命值的护盾。当护盾被打破后，他会解除骑乘状态，暂时变为不可被选取状态，获得70%/80%/ 110%攻击速度并使每第4次攻击造成他150%攻击力的伤害。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/kled-violent-tendencies.png","skillName":"暴烈秉性","skillType":"被动","price":"1","recEquip":""},{"TFTID":"271","chessId":"266","displayName":"亚托克斯","hero_EN_name":"TFT5_Aatrox","title":"暗裔剑魔","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/271.png","jobIds":"5004","raceIds":"5107","skillIntroduce":"【亚托克斯】打击他的目标，造成他 260/280/360%攻击力的伤害，并治疗自身200/300/450生命值。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/aatrox-deathbringer-strike.png","skillName":"赐死打击","skillType":"主动","price":"1","recEquip":""},{"TFTID":"315","chessId":"412","displayName":"锤石","hero_EN_name":"TFT5_Thresh","title":"魂锁典狱长","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/315.png","jobIds":"5007","raceIds":"5101","skillIntroduce":"【锤石】抛出他的镰刀，链住相距最远的敌人，造成175/350/800魔法伤害并将其拉拽向【锤石】，持续2/3/4秒。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/thresh-death-sentence.png","skillName":"死亡判决","skillType":"主动","price":"2","recEquip":""},{"TFTID":"282","chessId":"427","displayName":"艾翁","hero_EN_name":"TFT5_Ivern","title":"翠神","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/282.png","jobIds":"5006,5005","raceIds":"5113","skillIntroduce":"【艾翁】召唤他的哨兵好友【小菊】来并肩作战，并在周围1格内施放一次冲击波。【小菊】的最大生命值和法术强度等于艾翁的最大生命值和法术强度。如果【小菊】已经被召唤出来了，艾翁会提高小菊 100/150/300%的法术强度，并且立即施放一次冲击波。【小菊】会与【艾翁】一起升星，在升星时，【小菊】除了获得生命值增长外，还会获得额外90攻击力。\r\n小菊生命值：1500/2400/10000，小菊的护盾600/900/3000","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/ivern-daisy.png","skillName":"小菊！","skillType":"主动","price":"4","recEquip":""},{"TFTID":"284","chessId":"429","displayName":"卡莉丝塔","hero_EN_name":"TFT5_Kalista","title":"复仇之矛","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/284.png","jobIds":"5004","raceIds":"5106","skillIntroduce":"卡莉丝塔向长远的敌人投掷长矛，对其所攻击的第一个敌人造成基于卡莉丝塔180/200/220%攻击力的伤害，外加额外的350/600/900物理伤害。如果这杀死了目标，则长矛继续前进，并将对它命中的下一个目标造成额外伤害。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/kalista-pierce.png","skillName":"刺穿","skillType":"主动","price":"1","recEquip":""},{"TFTID":"337","chessId":"497","displayName":"洛","hero_EN_name":"TFT5_Rakan","title":"幻翎","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/337.png","jobIds":"5005","raceIds":"5114","skillIntroduce":"洛朝他的目标发射一根羽毛，对命中的首个敌人造成350/500/800魔法伤害。随后洛会治疗所有附近的友军，数额为各友军35/50/70%的已损失生命值，并在羽毛击杀了一名敌人时提升治疗半径。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/rakan-battle-dance.png","skillName":"微光飞翎","skillType":"主动","price":"3","recEquip":""},{"TFTID":"272","chessId":"523","displayName":"厄斐琉斯","hero_EN_name":"TFT5_Aphelios","title":"残月之肃","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/272.png","jobIds":"5002","raceIds":"5102","skillIntroduce":"【厄斐琉斯】朝他的目标发射黑暗能量。一旦触碰到一名敌人，该目标四周大范围内的5/5/10名敌人们都会被标记，随后【厄斐琉斯】会朝他们所有人同时进行攻击，对每人造成基于他350/375/450%攻击力和额外150/200/400的物理伤害。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/aphelios-dark-vigil.png","skillName":"黯蚀夜凝","skillType":"主动","price":"4","recEquip":""},{"TFTID":"306","chessId":"526","displayName":"芮尔","hero_EN_name":"TFT5_Rell","title":"镕铁少女","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/306.png","jobIds":"5011","raceIds":"5107,5111","skillIntroduce":"【芮尔】跳向空中，将自身与相距最远的友军进行绑定，当她着陆时，使路径上的所有敌人昏迷1.5/2/8秒，并且会为路径上的所有友军提供一层300/450/3000的护盾，持续4秒。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/rell-attract-and-repel.png","skillName":"挥斥","skillType":"主动","price":"4","recEquip":""},{"TFTID":"340","chessId":"555","displayName":"派克","hero_EN_name":"TFT5_Pyke","title":"血港鬼影","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/340.png","jobIds":"5001","raceIds":"5114","skillIntroduce":"派克在他的当前位置留下一个魅影，然后冲刺到相距最远的目标身后。在1秒后，魅影会回到派克处，对其途经的所有敌人造成150 / 225 / 325魔法伤害和 1.5 / 2 / 2.5秒晕眩效果。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/pyke-phantom-undertow.png","skillName":"魅影浪洄","skillType":"主动","price":"2","recEquip":""},{"TFTID":"310","chessId":"875","displayName":"瑟提","hero_EN_name":"TFT5_Sett","title":"腕豪","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/310.png","jobIds":"5003","raceIds":"5110","skillIntroduce":"【瑟提】朝着他的目标轰出重拳，在一个锥形区域内引发冲击波，对区域内的所有敌人造成基于瑟提170/185/200%攻击力的物理伤害，并使其中的敌人降低20/25/40护甲，持续10秒。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/sett-haymaker.png","skillName":"蓄意轰拳","skillType":"主动","price":"2","recEquip":""},{"TFTID":"338","chessId":"887","displayName":"格温","hero_EN_name":"TFT5_Gwen","title":"灵罗娃娃","character_id":"","name":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/chess/338.png","jobIds":"5010","raceIds":"5115","skillIntroduce":"格温围着她的目标冲刺，并在她前方的一个锥形区域内进行3次快速剪击，每次剪击造成125/200/2222外加目标5%/8%/50%最大生命值的魔法伤害。剪击会从目标处窃取2/2/11护甲和魔法抗性。每隔一次施放，格温就会进行双倍的剪击。","skillImage":"https://wegame.gtimg.com/g.26-r.c2d3c/helper/tft/s5/images/skill/gwen-skip-n-slash.png","skillName":"断续疾走","skillType":"主动","price":"5","recEquip":""}]